# Generated by Django 4.0.4 on 2022-05-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractproduct',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
