# Generated by Django 4.0.4 on 2022-05-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('contracts', '0002_alter_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='projects.project', verbose_name='Project'),
        ),
    ]
