# Generated by Django 4.0.4 on 2022-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=256, verbose_name='Page')),
                ('query', models.CharField(max_length=256, verbose_name='Query')),
                ('count', models.BigIntegerField(default=0, verbose_name='Visits')),
            ],
            options={
                'verbose_name': 'Search query',
                'verbose_name_plural': 'Search queries',
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=256, unique=True, verbose_name='Page')),
                ('count', models.BigIntegerField(default=0, verbose_name='Visits')),
            ],
            options={
                'verbose_name': 'Visits',
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
