# Generated by Django 4.0.3 on 2022-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.FloatField(default=1, verbose_name='Rate'),
        ),
    ]
