# Generated by Django 4.0.4 on 2022-05-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_company'),
        ('companies', '0001_initial'),
        ('bank_accounts', '0002_alter_account_company'),
        ('contracts', '0002_alter_contract_company'),
        ('Baumanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrole',
            name='author',
        ),
        migrations.RemoveField(
            model_name='companyrole',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='companies.company', verbose_name='Company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyRole',
        ),
    ]
