# Generated by Django 4.0.3 on 2022-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='mymessage',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
