# Generated by Django 4.0.4 on 2022-05-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='label',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contractlabel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contractlabel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='contractlabel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contractproduct',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractproduct',
            name='product',
        ),
    ]
