# Generated by Django 4.0.3 on 2022-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0002_remove_company_create_remove_company_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='company',
            name='role',
        ),
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.ManyToManyField(to='Baumanagement.companyrole'),
        ),
    ]
