# Generated by Django 4.0.4 on 2022-05-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0002_remove_companyrole_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='label',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projectlabel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectlabel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='projectlabel',
            name='updated_by',
        ),
    ]
