# Generated by Django 4.0.3 on 2022-04-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0002_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.currency', verbose_name='Currency'),
        ),
    ]
