# Generated by Django 4.0.3 on 2022-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0002_mymessage_comment_ids_mymessage_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='datetime_format',
            field=models.CharField(default='%Y-%m-%d %H:%M', max_length=256, verbose_name='Datetime format'),
        ),
    ]
