# Generated by Django 4.0.3 on 2022-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0003_alter_company_email_remove_company_role_company_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.CharField(default='', max_length=256, verbose_name='Geschäftsführer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=256, verbose_name='PLZ Stadt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Straße Hausnummer'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Firmenname'),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.ManyToManyField(to='Baumanagement.companyrole', verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(max_length=128, verbose_name='Rufnummer'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Rolle'),
        ),
    ]
