# Generated by Django 4.0.3 on 2022-04-08 07:08

import django.db.models.deletion
from django.db import migrations, models

def main(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ProjectRole = apps.get_model("Baumanagement", "ProjectRole")
    ProjectRole.objects.using(db_alias).get_or_create(name="Sonstige", created_by_id=1)


class Migration(migrations.Migration):
    dependencies = [
        ('Baumanagement', '0003_projectrole'),
    ]

    operations = [
        migrations.RunPython(main),
    ]
