# Generated by Django 4.0.3 on 2022-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0003_contract_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='', max_length=3, verbose_name='Symbol'),
        ),
    ]
