# Generated by Django 4.0.4 on 2022-05-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0003_settings_datetime_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='date_format',
            field=models.CharField(default='%Y-%m-%d', max_length=256, verbose_name='Date format'),
        ),
    ]
