# Generated by Django 4.0.3 on 2022-04-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Baumanagement', '0003_projectrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.RESTRICT, related_name='projects',
                                    to='Baumanagement.projectrole', verbose_name='Role'),
            preserve_default=False,
        ),
    ]
