# Generated by Django 4.0.4 on 2022-05-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_project'),
        ('settings', '0002_alter_settings_active_project'),
        ('Baumanagement', '0003_remove_project_author_remove_project_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectLabel',
        ),
    ]
