# Generated by Django 4.0.3 on 2022-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0004_remove_company_contact_company_ceo_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.ManyToManyField(related_name='role', to='Baumanagement.companyrole', verbose_name='Rolle'),
        ),
    ]
