# Generated by Django 4.0.4 on 2022-05-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0004_alter_bill_contract_alter_payment_contract_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
