# Generated by Django 4.0.4 on 2022-05-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0004_settings_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='date_format',
            field=models.CharField(default='%d.%m.%y', max_length=256, verbose_name='Date format'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='datetime_format',
            field=models.CharField(default='%d.%m.%Y %H:%M', max_length=256, verbose_name='Datetime format'),
        ),
    ]
