# Generated by Django 4.0.3 on 2022-04-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0004_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bills_from', to='Baumanagement.account', verbose_name='Write-off account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bills_to', to='Baumanagement.account', verbose_name='Write-off account'),
        ),
    ]
