# Generated by Django 4.0.3 on 2022-03-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0005_alter_company_address_alter_company_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tel',
            new_name='phone',
        ),
    ]
