# Generated by Django 4.0.4 on 2022-05-03 08:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0005_alter_settings_date_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_netto_positiv', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount netto')),
                ('amount_brutto_positiv', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount brutto')),
                ('vat', models.FloatField(default=19, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='VAT %')),
                ('count', models.FloatField(default=1.0, verbose_name='Count')),
                ('use_product_price', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='Baumanagement.contract', verbose_name='Contract')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Baumanagement.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
