# Generated by Django 4.0.3 on 2022-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0005_payment_account_from_payment_account_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AddField(
            model_name='bill',
            name='amount_netto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amount_netto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_netto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount netto'),
        ),
    ]
