# Generated by Django 4.0.3 on 2022-04-08 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baumanagement', '0005_project_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectRole',
            new_name='ProjectType',
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='role',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects',
                                    to='Baumanagement.projecttype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Type'),
        ),

    ]
