# Generated by Django 4.0.3 on 2022-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0006_rename_tel_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.ManyToManyField(related_name='companies', to='Baumanagement.companyrole', verbose_name='Rolle'),
        ),
    ]
