# Generated by Django 4.0.3 on 2022-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0006_bill_amount_brutto_positiv_bill_amount_netto_positiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount brutto'),
        ),
    ]
