# Generated by Django 4.0.4 on 2022-05-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0006_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
