# Generated by Django 4.0.3 on 2022-04-08 07:08
from datetime import datetime

from django.db import migrations
from django.utils.timezone import make_aware


def main(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    if not User.objects.filter(username='system'):
        usr = User.objects.create(username='system', last_login=make_aware(datetime.now()))
    else:
        usr = User.objects.get(username='system')

    db_alias = schema_editor.connection.alias
    ContractType = apps.get_model("Baumanagement", "ContractType")
    ContractType.objects.using(db_alias).get_or_create(name="Sonstige", created_by_id=usr.id)


class Migration(migrations.Migration):
    dependencies = [
        ('Baumanagement', '0007_contracttype'),
    ]

    operations = [
        migrations.RunPython(main),
    ]
