# Generated by Django 4.0.3 on 2022-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0007_account_created_by_bill_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=256, verbose_name='Code'),
        ),
    ]
