# Generated by Django 4.0.3 on 2022-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0007_alter_company_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Anzahl'),
            preserve_default=False,
        ),
    ]
