# Generated by Django 4.0.4 on 2022-05-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0007_delete_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyMessage',
        ),
    ]
