# Generated by Django 4.0.3 on 2022-04-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0007_alter_bill_amount_brutto_positiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bills_to', to='Baumanagement.account', verbose_name='Top-up account'),
        ),
    ]
