# Generated by Django 4.0.4 on 2022-05-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0008_delete_mymessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
