# Generated by Django 4.0.3 on 2022-03-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0008_companyrole_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Rufnummer'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Rolle'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Auftrag')),
                ('code', models.CharField(max_length=256, verbose_name='Kode')),
                ('address', models.CharField(max_length=256, verbose_name='Adresse')),
                ('city', models.CharField(max_length=256, verbose_name='PLZ Stadt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_projects', to='Baumanagement.company', verbose_name='Bearbeiter')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_projects', to='Baumanagement.company', verbose_name='Auftraggeber')),
            ],
        ),
    ]
