# Generated by Django 4.0.3 on 2022-04-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Baumanagement', '0008_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts',
                                    to='Baumanagement.contracttype', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
