# Generated by Django 4.0.3 on 2022-04-08 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baumanagement', '0010_rename_type_project_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectType',
            new_name='ProjectTag',
        ),
    ]
