# Generated by Django 4.0.3 on 2022-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0010_remove_project_customer_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Projekt'),
        ),
    ]
