# Generated by Django 4.0.3 on 2022-04-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0011_rename_projecttype_projecttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.contracttype', verbose_name='Type'),
        ),
    ]
