# Generated by Django 4.0.3 on 2022-04-08 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baumanagement', '0012_alter_contract_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractType',
            new_name='ContractTag',
        ),
    ]
