# Generated by Django 4.0.3 on 2022-03-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0012_project_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Unternehmen', 'verbose_name_plural': 'Unternehmen'},
        ),
        migrations.AlterModelOptions(
            name='companyrole',
            options={'verbose_name': 'Rolle', 'verbose_name_plural': 'Rollen'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekte'},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Auftrag')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.company', verbose_name='Bearbeiter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Auftrag',
                'verbose_name_plural': 'Aufträge',
            },
        ),
    ]
