# Generated by Django 4.0.3 on 2022-04-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0013_rename_contracttype_contracttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.contracttag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='Baumanagement.projecttag', verbose_name='Tag'),
        ),
    ]
