# Generated by Django 4.0.3 on 2022-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0013_alter_company_options_alter_companyrole_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
