# Generated by Django 4.0.3 on 2022-04-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0015_alter_company_name_alter_companyrole_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount_brutto',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='amount_netto',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='amount_brutto',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='amount_netto',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_brutto',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_netto',
        ),
    ]
