# Generated by Django 4.0.3 on 2022-03-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0015_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrole',
            name='count',
        ),
    ]
