# Generated by Django 4.0.3 on 2022-04-10 20:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0016_remove_bill_amount_brutto_remove_bill_amount_netto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount_netto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount netto'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vat',
            field=models.FloatField(default=19, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='VAT %'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_netto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount netto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vat',
            field=models.FloatField(default=19, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='VAT %'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_brutto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_netto_positiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount netto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vat',
            field=models.FloatField(default=19, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='VAT %'),
        ),
    ]
