# Generated by Django 4.0.3 on 2022-04-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0017_alter_bill_amount_brutto_positiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Baumanagement.contracttag'),
        ),
    ]
