# Generated by Django 4.0.3 on 2022-03-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0017_alter_payment_amount_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Betrag'),
            preserve_default=False,
        ),
    ]
