# Generated by Django 4.0.3 on 2022-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0018_contracttag_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttag',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name'),
        ),
    ]
