# Generated by Django 4.0.3 on 2022-03-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0018_contract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Projektname'),
        ),
    ]
