# Generated by Django 4.0.3 on 2022-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0019_alter_contracttag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttag',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
