# Generated by Django 4.0.3 on 2022-03-21 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0021_bill_created_bill_updated_company_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Datum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert'),
        ),
    ]
