# Generated by Django 4.0.3 on 2022-03-21 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0022_bill_date_payment_date_alter_bill_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Datum'),
            preserve_default=False,
        ),
    ]
