# Generated by Django 4.0.3 on 2022-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0024_alter_bill_name_alter_payment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='amount_brutto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bruttobetrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='amount_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nettobetrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='vat',
            field=models.FloatField(default=0, verbose_name='MWSt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='amount_brutto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bruttobetrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='amount_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nettobetrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='vat',
            field=models.FloatField(default=0, verbose_name='MWSt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_brutto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bruttobetrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nettobetrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='vat',
            field=models.FloatField(default=0, verbose_name='MWSt'),
            preserve_default=False,
        ),
    ]
