# Generated by Django 4.0.3 on 2022-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0026_company_land_company_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='land',
            field=models.CharField(blank=True, default='Deutschland', max_length=256, verbose_name='Land'),
        ),
    ]
