# Generated by Django 4.0.3 on 2022-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0026_product_description_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=7, verbose_name='Product type'),
        ),
    ]
