# Generated by Django 4.0.3 on 2022-04-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0027_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='Baumanagement.currency', verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
