# Generated by Django 4.0.3 on 2022-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0028_payment_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bills',
            field=models.ManyToManyField(blank=True, null=True, related_name='payments', to='Baumanagement.bill', verbose_name='Verbindende Rechnungen'),
        ),
    ]
