# Generated by Django 4.0.3 on 2022-03-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0030_alter_payment_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bills',
        ),
    ]
