# Generated by Django 4.0.3 on 2022-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0031_remove_payment_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='payment',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
