# Generated by Django 4.0.3 on 2022-04-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0031_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments_from', to='Baumanagement.account', verbose_name='Write-off account'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments_to', to='Baumanagement.account', verbose_name='Top-up account'),
        ),
    ]
