# Generated by Django 4.0.3 on 2022-04-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0032_alter_payment_account_from_alter_payment_account_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='Baumanagement.contracttag', verbose_name='Classify label under'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='Baumanagement.productcategory', verbose_name='Classify category under'),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='Baumanagement.projecttag', verbose_name='Classify label under'),
        ),
    ]
