# Generated by Django 4.0.3 on 2022-03-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0032_bill_open_payment_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='contract',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
