# Generated by Django 4.0.3 on 2022-03-25 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0033_company_open_companyrole_open_contract_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vat',
            field=models.FloatField(default=19, verbose_name='MWSt %'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vat',
            field=models.FloatField(default=19, verbose_name='MWSt %'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vat',
            field=models.FloatField(default=19, verbose_name='MWSt %'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('name', models.CharField(max_length=256, verbose_name='Zahlung')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d', verbose_name='Datei')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='Baumanagement.bill')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='Baumanagement.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='Baumanagement.contract')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='Baumanagement.payment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='Baumanagement.project')),
            ],
            options={
                'verbose_name': 'Datei',
                'verbose_name_plural': 'Dateien',
            },
        ),
    ]
