# Generated by Django 4.0.3 on 2022-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0034_mymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
    ]
