# Generated by Django 4.0.3 on 2022-04-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0035_mymessage_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymessage',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
