# Generated by Django 4.0.3 on 2022-04-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0037_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='sort',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
