# Generated by Django 4.0.3 on 2022-03-28 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0037_alter_file_file_alter_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyrole',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount_brutto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount_netto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bills', to='Baumanagement.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Bill name'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vat',
            field=models.FloatField(default=19, verbose_name='VAT %'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(blank=True, max_length=256, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=256, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=256, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.ManyToManyField(related_name='companies', to='Baumanagement.companyrole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_brutto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_netto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Contract name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vat',
            field=models.FloatField(default=19, verbose_name='VAT %'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_brutto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount brutto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_netto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount netto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='Baumanagement.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Payment name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vat',
            field=models.FloatField(default=19, verbose_name='VAT %'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(max_length=256, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=256, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='Baumanagement.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
