# Generated by Django 4.0.3 on 2022-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0038_settings_date_from_settings_date_to_settings_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(blank=True, max_length=256, verbose_name='Bank'),
        ),
    ]
