# Generated by Django 4.0.3 on 2022-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0039_companyrole_created_companyrole_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=256, verbose_name='City'),
        ),
    ]
