# Generated by Django 4.0.3 on 2022-04-14 19:08

import Baumanagement.models.models_currency
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0039_account_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_currency',
            field=models.ForeignKey(default=Baumanagement.models.models_currency.Currency.get_EUR_id, on_delete=django.db.models.deletion.RESTRICT, to='Baumanagement.currency'),
        ),
    ]
