# Generated by Django 4.0.3 on 2022-04-14 19:14

import Baumanagement.models.models_currency
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0040_settings_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=Baumanagement.models.models_currency.Currency.get_EUR_id, on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='Baumanagement.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(default=Baumanagement.models.models_currency.Currency.get_EUR_id, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='Baumanagement.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=Baumanagement.models.models_currency.Currency.get_EUR_id, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='Baumanagement.currency', verbose_name='Currency'),
        ),
    ]
