# Generated by Django 4.0.3 on 2022-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0040_alter_project_address_alter_project_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Open'),
        ),
    ]
