# Generated by Django 4.0.3 on 2022-03-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0041_file_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='file',
            name='company',
        ),
        migrations.RemoveField(
            model_name='file',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='file',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
    ]
