# Generated by Django 4.0.3 on 2022-04-14 19:53

import Baumanagement.models.abstract
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Baumanagement', '0042_alter_account_created_by_alter_bill_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='created_by',
            field=models.ForeignKey(default=Baumanagement.models.abstract.get_system_user_id, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
