# Generated by Django 4.0.3 on 2022-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0043_bill_files_company_files_contract_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='company',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Files'),
        ),
    ]
