# Generated by Django 4.0.3 on 2022-04-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0044_alter_settings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='img',
            field=models.ImageField(height_field=100, null=True, upload_to='', verbose_name='Image', width_field=100),
        ),
    ]
