# Generated by Django 4.0.3 on 2022-03-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0044_alter_bill_files_alter_company_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='open',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated',
        ),
    ]
