# Generated by Django 4.0.3 on 2022-04-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0045_settings_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
    ]
