# Generated by Django 4.0.3 on 2022-03-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0046_alter_bill_files_alter_company_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='files',
            new_name='file_ids',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='files',
            new_name='file_ids',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='files',
            new_name='file_ids',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='files',
            new_name='file_ids',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='files',
            new_name='file_ids',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d', verbose_name='Files'),
        ),
    ]
