# Generated by Django 4.0.3 on 2022-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0047_rename_files_bill_file_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='company',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Files'),
        ),
    ]
