# Generated by Django 4.0.3 on 2022-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0047_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=256, unique=True, verbose_name='Link')),
                ('count', models.BigIntegerField(default=0, verbose_name='Visits')),
            ],
            options={
                'verbose_name': 'Visits',
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
