# Generated by Django 4.0.3 on 2022-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0048_searchqueries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchqueries',
            options={'verbose_name': 'Search query', 'verbose_name_plural': 'Search queries'},
        ),
        migrations.AddField(
            model_name='searchqueries',
            name='query',
            field=models.CharField(default='', max_length=256, verbose_name='Query'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchqueries',
            name='page',
            field=models.CharField(max_length=256, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='page',
            field=models.CharField(max_length=256, unique=True, verbose_name='Page'),
        ),
    ]
