# Generated by Django 4.0.3 on 2022-03-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0049_file_created_file_open_file_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('open', models.BooleanField(default=True, verbose_name='Open')),
                ('file_ids', models.JSONField(blank=True, default=list, verbose_name='Files')),
                ('name', models.CharField(max_length=256, verbose_name='Company name')),
                ('IBAN', models.CharField(blank=True, max_length=256, verbose_name='IBAN')),
                ('BIC', models.CharField(blank=True, max_length=256, verbose_name='BIC')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='Baumanagement.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
