# Generated by Django 4.0.3 on 2022-03-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0051_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='bill',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='company',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='contract',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='file',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='payment',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='project',
            name='comment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='Baumanagement.company', verbose_name='Company'),
        ),
    ]
