# Generated by Django 4.0.3 on 2022-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baumanagement', '0054_rename_text_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Files'),
        ),
    ]
