# Generated by Django 4.0.4 on 2022-05-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_delete_mymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.TextField(verbose_name='Notification'),
        ),
    ]
